### ISSUE TITLE
COLT dot products vs. custom dot products

### ISSUE THREAD

**Issue by akapila** [mmastroianni/fast-lsh#1]
I added benchmarking code to compare COLT dot products to my own custom dot product.  It is in org.fastlsh.hash.ColtVsCustomDotProduct in src/test.  It shows that my custom, naive dot product is an order of magnitude than using COLT.  I think we should just use our own custom dense and sparse vectors and custom dot product.  I'll go about implementing this.

**Comment by also** [comment]
Your `dot` function has no side effects. When I run it, it is optimized away completely. It also just computes the sum of the elements in the two vectors, rather than the dot product.
