### ISSUE TITLE
Latest refactoring of indexer code

### ISSUE THREAD

**Issue by mmastroianni** [mmastroianni/fast-lsh#3]
As far as I can see, this latest one was entirely stylistic. When I merged back the removal of the colt libraries from the dense_only thread and ran my timings, I found that I had lost 17 seconds on 10M rows in the threaded indexer.

I know that for really large stuff we want people to use hadoop, but a 25% slowdown isn't trivial.

**Comment by also** [comment]
The description was empty for some reason, so I pasted it from the notification email.

**Comment by also** [comment]
So, I don't see any merge, but it looks like this was invalid?

Was this comparing the branch with the call to reset (introduced in bdbfa1c1623019b8cfae11028e1e24c1400df6a1) with  master which never had that change?

**Comment by mmastroianni** [comment]
It turned out to just be not resetting the buffers, which I had been doing in the other branch: this was as much my fault in the merge as anything. It was surprisingly painful to ferret out last night.

**Comment by mmastroianni** [comment]
Yep. As I said, I should have merged it in from my branch.
